id: d90aceb284c14d8b87c8aa1e8875b00c
title: Toh_736-The_Dharani_of_Parnasavari-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-094-013
  eft-text-version: 1.1.2 2020
